[build]
  base = "/"
  publish = "frontend/dist"
  command = "cd frontend && npm install && npm run build"

[build.environment]
  NODE_VERSION = "20"

# Redirect API requests to your backend server
# IMPORTANT: Update this URL to point to your actual deployed backend
# You can also remove this redirect if you're using VITE_API_URL for direct API calls
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-server.com/api/:splat"
  status = 200
  force = true

# SPA redirect - all non-API routes should serve index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables should be set in Netlify dashboard
# Required for frontend:
# VITE_API_URL=https://your-backend-server.com
